// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJMe67sZvIjQYQXa4ytBZLlS3IUR00Qro',
    appId: '1:960157170257:web:ea5d60388da05b421ed670',
    messagingSenderId: '960157170257',
    projectId: 'chatgpt-63c03',
    authDomain: 'chatgpt-63c03.firebaseapp.com',
    storageBucket: 'chatgpt-63c03.appspot.com',
    measurementId: 'G-X1TBRHZ05N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEa_uv0XNNkMh60vihoOTtN2DXbPW0Jgg',
    appId: '1:960157170257:android:60e4f44dd2a53c251ed670',
    messagingSenderId: '960157170257',
    projectId: 'chatgpt-63c03',
    storageBucket: 'chatgpt-63c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWLg_cqBzuXqyYoQ8k_EciNSPOKDrOMoU',
    appId: '1:960157170257:ios:c2315292fe40ffd91ed670',
    messagingSenderId: '960157170257',
    projectId: 'chatgpt-63c03',
    storageBucket: 'chatgpt-63c03.appspot.com',
    iosClientId: '960157170257-4obs13ac6opfeb0958jic7thktqja5no.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatgpt',
  );
}
